name: Build and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - name: Use Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          npm install

      - name: Build
        run: |
          npm run build

      - name: Upload static HTML artifact
        uses: actions/upload-artifact@v4
        with:
          name: static-html
          path: dist/

  deploy-pr-preview:
    needs: build
    permissions:
      deployments: write
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v4
      - name: Download static HTML artifact
        uses: actions/download-artifact@v4
        with:
          name: static-html
          path: dist

      - name: Upload website to S3
        uses: ./.github/actions/minio-upload
        with:
          url: "https://s3-eu-central-2.ionoscloud.com"
          accessKey:  ${{ secrets.S3_ACCESS_KEY }}
          secretKey:  ${{ secrets.S3_SECRET_KEY }}
          bucket: sgc-dashboard-preview-d98d665658f0
          source_dir: dist/
          target_dir: /pr/${{ github.event.number }}/${{github.event.pull_request.head.sha}}

      - uses: chrnorm/deployment-action@v2
        name: Create GitHub deployment
        id: deployment
        with:
          token: '${{ github.token }}'
          environment-url: "https://sgc-dashboard-preview-d98d665658f0.s3-eu-central-2.ionoscloud.com/pr/${{github.event.number}}/${{github.event.pull_request.head.sha}}/index.html"
          environment: preview-pr-${{github.event.number}}
          initial-status: success

  deploy-main:
    needs: build
    permissions:
      deployments: write
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v4
      - name: Download static HTML artifact
        uses: actions/download-artifact@v4
        with:
          name: static-html
          path: dist
      - name: Upload website to S3
        uses: ./.github/actions/minio-upload
        with:
          url: "https://s3-eu-central-2.ionoscloud.com"
          accessKey:  ${{ secrets.S3_ACCESS_KEY }}
          secretKey:  ${{ secrets.S3_SECRET_KEY }}
          bucket: sgc-dashboard-d0cafa4cdadf
          source_dir: dist/
          target_dir: /
      - uses: chrnorm/deployment-action@v2
        name: Create GitHub deployment
        id: deployment
        with:
          token: '${{ github.token }}'
          environment-url: "https:/ sgc-dashboard-d0cafa4cdadf.s3-eu-central-2.ionoscloud.com/index.html"
          environment: production
          initial-status: success
